apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      #version: ">=2.4.1"
  install:
    remediation:
      retries: -1
  interval: 24h0m0s
  values:
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        interval: 60s
        labels: {}
        path: /metrics
        prometheusInstance: default
        scrapeTimeout: 30s
        targetPort: 9402