apiVersion: logging.banzaicloud.io/v1alpha1
kind: Logging
metadata:
  name: nuamx-logging
spec:
  controlNamespace: logging
  fluentbit:
    inputTail:
      storage.type: filesystem
      Mem_Buf_Limit: 50MB
    bufferStorageVolume:
      emptyDir: {}
    resources:
      limits:
        memory: 256M
        cpu: 200m
      requests:
        memory: 128M
        cpu: 100m
  fluentd:
    scaling:
      replicas: 1 # 2
      drain:
        enabled: true
    disablePvc: true
    bufferStorageVolume:
      emptyDir: {}
    resources:
      limits:
        memory: 256M
        cpu: 200m
      requests:
        memory: 128M
        cpu: 100m
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - fluentd
          topologyKey: "kubernetes.io/hostname"
---
apiVersion: logging.banzaicloud.io/v1alpha1
kind: ClusterOutput
metadata:
  name: nuamx-logging-output
  namespace: logging
spec:
  loki:
    buffer:
      flush_mode: immediate
    configure_kubernetes_labels: true
    extract_kubernetes_labels: true
    url: 'http://loki-stack.logging.svc.cluster.local:3100'
---
apiVersion: logging.banzaicloud.io/v1alpha1
kind: ClusterFlow
metadata:
  name: nuamx-logging-flow
  namespace: logging
spec:
  globalOutputRefs:
    - nuamx-logging-output
  match:
    - select: {} # select all logs