apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
spec:
  releaseName: loki-stack
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: ">=2.9.11"
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 24h0m0s
  values:
    grafana:
      enabled: true
      image:
        tag: latest
      ingress:
        enabled: false
      persistence:
        enabled: true
        storageClassName: managed-csi
      sidecar:
        datasources:
          enabled: true
    loki: # loki subchart in monolithic mode
      enabled: true
      loki:
        commonConfig:
          replication_factor: 1
        storage:
          type: 'filesystem'
      singleBinary:
        replicas: 1
        persistence:
          enabled: true
          size: 30Gi
          storageClassName: managed-csi
    promtail:
      enabled: false
