
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: devops-vault
spec:
  releaseName: vault-operator
  chart:
    spec:
      chart: vault-operator
      sourceRef:
        kind: HelmRepository
        name: banzaicloud
        namespace: flux-system
      version: ">=1.19.0"
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  interval: 24h0m0s
  values:
    #nodeSelector:
    #  devops-core: enabled
