apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  releaseName: sealed-secrets
  targetNamespace: flux-system
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: '>=2.14.1'
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 1h0m0s
  upgrade:
    crds: CreateReplace
  values:
    # Default values for sealed-secrets.