
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      #version: "36.5.1" # fixed version to avoid automatic upgrades
      version: ">=52.1.0"
  timeout: 10m
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
  interval: 24h0m0s
  values:
    # Forcing Kubelet metrics scraping on http
    kubelet:
      enabled: true
      serviceMonitor:
        https: true
    # Disabling scraping of Master Nodes Components
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false
    grafana:
      plugins:
      - grafana-piechart-panel
    prometheusOperator:
      admissionWebhooks:
        enabled: false
      tls:
        enabled: false