apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: tracing
spec:
  releaseName: tempo
  chart:
    spec:
      chart: tempo-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  timeout: 10m
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
  interval: 24h0m0s
  values:
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
      zipkin:
        enabled: true
      jaeger:
        thriftCompact:
          enabled: true
        thriftHttp:
          enabled: true
      opencensus:
        enabled: true