---
name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: self-hosted
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"

    - run: mkdir pruebafolder

    - name: delete
      run: |
        cd /home/kevardila/actions-runner/_work
        rm -rf *
