---
name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: self-hosted
    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
        
    - run: echo "🎉 This job uses runner scale set runners!"

    - run: docker ps

  clean-shr:
    runs-on: self-hosted
    steps:
      - name: delete
        run: |
          cd /home/kevardila/actions-runner/_work
          rm -rf *
