name: Java Maven Build & Publish Artifact

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
#
jobs:
  versioning:
    uses: bvcco/lab_devops_templates/.github/workflows/CI-versioning-XaC.yml@feat/ARQPD-1230