apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logging-operator
spec:
  releaseName: logging-operator
  chart:
    spec:
      chart: logging-operator
      sourceRef:
        kind: HelmRepository
        name: banzaicloud
        namespace: flux-system
      version: ">=3.13.0"
  interval: 6h0m0s
  install:
    remediation:
      retries: -1
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    # Default values for logging-operator.